services:
  stream-server:
    build:
      context: ../
      dockerfile: docker-configs/Dockerfile
    environment:
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=50000
      - NETWORK_MTU=1500
      - LOG_LEVEL=CRITICAL
    volumes:
      - ./videos_volume:/opt/stream-server/videos_volume
    ports:
      - "50000:50000"
