FROM python:3.11

COPY . /opt/stream-server

WORKDIR /opt/stream-server

RUN apt-get update
RUN apt-get install libmediainfo-dev -y
RUN pip install -r requirements.txt


ENTRYPOINT [ "python3", "main.py" ]
